### ISSUE TITLE
groups

### ISSUE THREAD

**Issue by nickbetteridge** [dbuenzli/vg#10]
Am busy writing an editor at the moment and would like to use Vg for svg management - the doc states that groups are currently not implemented - is this likely to be implemented in the near future? Thanks, Nick

**Comment by dbuenzli** [comment]
What do you mean by groups ? There's no concept of groups in Vg.

**Comment by nickbetteridge** [comment]
Something along the lines of SVGGroup

**Comment by dbuenzli** [comment]
Ah you mean transparency/compositing groups. No, not planned.

**Comment by nickbetteridge** [comment]
OK, thanks
