### ISSUE TITLE
Example request: 

### ISSUE THREAD

**Issue by fxfactorial** [dbuenzli/vg#11]
I'm considering using this along with postgresl to create some simple graphs. 

I'm wondering if you could provide some examples that could show off a bar graph or maybe like a line graph, ideally both. 

Or maybe vg wouldn't be the best choice for this?

**Comment by dbuenzli** [comment]
> I'm wondering if you could provide some examples that could show off a bar graph or maybe like a line graph, ideally both.

See for example http://erratique.ch/software/vg/demos/rhtmlc#pie-ambiguity

> Or maybe vg wouldn't be the best choice for this?

Depends a bit. You may found the thing too low-level for label placement, see https://github.com/dbuenzli/vg/issues/6
