### ISSUE TITLE
jsoo 3.0

### ISSUE THREAD

**Issue by Freyr666** [dbuenzli/vg#15]
At the moment Vg package conflicts with "js_of_ocaml" {>= "3.0"}. Could you upgrade the package to add jsoo.3.0 support please?

**Comment by dbuenzli** [comment]
It shouldn't be too hard, I think it's just that @hhugo changed the packaging structure in an [undocumented manner](https://github.com/ocsigen/js_of_ocaml/blob/dcdf727d4d9ff803c36d59d7af3f5453b4550708/CHANGES#L8) which makes the build fail and I don't have the time to look into this at the moment. If you feel like giving it a look a PR would be welcome.

**Comment by dbuenzli** [comment]
The PR https://github.com/dbuenzli/vg/pull/16 doesn't work but it may be due to `js_of_ocaml` itself.

**Comment by dbuenzli** [comment]
Thanks to @Freyr666. This should be handled by https://github.com/ocaml/opam-repository/pull/10056
