### ISSUE TITLE
Broken link in documentation.

### ISSUE THREAD

**Issue by pveber** [dbuenzli/vg#18]
The link to standard PDF font metrics in `Vgr_pdf` is broken:

> (the font metrics can be downloaded here). 

The (broken) url is `https://partners.adobe.com/public/developer/font/index.html#pcfi`. Maybe the contents was moved to this url: `https://www.adobe.com/devnet/font.html`?

**Comment by dbuenzli** [comment]
Thanks @pveber for tracking the new location !
