### ISSUE TITLE
Cairo 0.6 removes labels

### ISSUE THREAD

**Issue by Chris00** [dbuenzli/vg#20]
[Cairo 0.6](https://github.com/ocaml/opam-repository/pull/12773) removes many labels `~x`, `~y` when they are not adding a clear benefit.  The rationale is that these labels were added at a time where merlin did not exists and could serve as quick documentation by requesting the signature.  Now that dune default mode requires labels, many users will feel compelled to add them... which makes many calls quite heavy.  Since `Vg` uses some of these labels, it needs to be adapted.

**Comment by dbuenzli** [comment]
> Now that dune default mode requires labels, many users will feel compelled to add them...

What does that mean ?

**Comment by Chris00** [comment]
On 10 October 2018 at 15:30 GMT, Daniel Bünzli wrote:
>
>  Now that dune default mode requires labels, many users will feel compelled to
>  add them...
>
> What does that mean ?

The default flags in Dune require labels to be present.

**Comment by dbuenzli** [comment]
> The default flags in Dune require labels to be present.

Ah didn't know that. What a stupid idea to alter the default flags of the compiler.
