### ISSUE TITLE
How to right-align text?

### ISSUE THREAD

**Issue by mjambon** [dbuenzli/vg#24]
Assuming horizontal, left-to-right text, I couldn't find a way to place the right-end of the text where I want.

I wasn't sure where to ask the question, so I [asked on StackOverflow](https://stackoverflow.com/questions/57938318/how-to-right-align-text-with-the-vg-library-in-ocaml). Feel free to delete this Github ticket.

PS: the library and its documentation is a real pleasure to use. Thank you.

**Comment by dbuenzli** [comment]
Basically Vg does not provide this, it's a low level API and I don't think it's the right place to provide it. A longer discussion about this [here](https://github.com/dbuenzli/vg/issues/6#issuecomment-60067463).

**Comment by pveber** [comment]
In case it may help, I reused a code written by @dbuenzli to form a module named `Vg_text`, which provides a function to calculate the length of a given text (I failed to expand this to height calculation though). This module can be found in [a beta lib I'm working on](https://github.com/pveber/croquis/tree/master/lib).
