### ISSUE TITLE
Documentation for some modules missing

### ISSUE THREAD

**Issue by joelburget** [dbuenzli/vg#27]
Hi Daniel, I noticed that documentation for some modules (eg [Vg.I](https://erratique.ch/software/vg/doc/Vg.I.html) and [Vg.Vgr](https://erratique.ch/software/vg/doc/Vg.Vgr.html)) is missing on your website.

**Comment by joelburget** [comment]
Sorry about that, I must have had an old version of the Vg top-level docs open or something. After I reloaded the paths are correct (links to eg [Vg.I](https://erratique.ch/software/vg/doc/Vg/I/index.html) are now working).

**Comment by dbuenzli** [comment]
Yeah there was a switch from `ocamldoc` to `odoc` which breaks links.
