### ISSUE TITLE
Can't make vg.cairo work

### ISSUE THREAD

**Issue by davesnx** [dbuenzli/vg#29]
Hello @dbuenzli 

I successfully made vg with SVG working great, but I want to change to render pngs. While using vg.cairo, I'm able to install it but fails while building.

OCaml 4.10 (I tried with 4.12 as well)
dune 2.8.5

```Error: Library "vg.cairo" in /home/runner/.opam/4.10.0/lib/vg is hidden```

I'm unsure what "vg is hidden" means.

Tried to re-install vg, re-install cairo2 and removed META files.

Thanks!

**Comment by dbuenzli** [comment]
> I'm unsure what "vg is hidden" means.

I have never seen this message either is it a `dune` thing ? 

Can you please try the minimal example and compilation instructions [here](https://erratique.ch/software/vg/doc/Vg/index.html#mincairomem).

**Comment by davesnx** [comment]
Weird, using the steps from the docs I got another warning regarding cairo2 missing which It wasn't... Then I nuke the opam switch and started again and everything seems to work fine, with either ocamlfind either dune.

Sorry for the trouble.

**Comment by dbuenzli** [comment]
Hé no problem. Glad that is works now.
