### ISSUE TITLE
Compilation error with b0

### ISSUE THREAD

**Issue by pveber** [dbuenzli/vg#35]
When trying to compile using `b0`:

```sh
$ opam source --dev-repo vg
Successfully fetched vg development repo to ./vg/
$ cd vg
$ b0
[FAIL] [ocamlopt][2]: (b0 file log --id 21)
File "/home/pveber/tmp/vg/B0.ml", line 19, characters 19-21:
Error: Unbound value ~/

b0: [ERROR] Could not compile B0 file /home/pveber/tmp/vg/B0.ml
```
It kind of looks like an automatic replace that went bad, but maybe I missed something.

**Comment by dbuenzli** [comment]
Try with `opam pin b0 --dev`, if it still doesn't work please use `topkg build`, I have a bunch of private changes in `b0` that are waiting a bit to be pushed for technical reasons.

**Comment by pveber** [comment]
Sorry, I should have checked the `opam` file first. It worked invoking 
```
ocaml pkg/pkg.ml build
```
Thanks!
