### ISSUE TITLE
Invalid SVG matrix transformation?

### ISSUE THREAD

**Issue by johnridesabike** [dbuenzli/vg#38]
I'm not 100% sure if I'm just misunderstanding something, but this looks like a bug. I tried making a basic "hello world" image in Vg and noticed my transforms weren't doing anything. After looking at the SVG output, I saw that Vg is outputting code like `transform="transform(...`. However, I don't believe that `transform` is an SVG transform function. When I manually edit the output to use the `matrix` function instead, the SVG renders as I expect.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform#transform_functions

https://github.com/dbuenzli/vg/blob/d28731797290a35fb965d679baa5960c7610f3e8/src/vgr_svg.ml#L72

**Comment by dbuenzli** [comment]
Indeed you are correct. Thanks for the report. 

I'm surprised it took so long to be discovered, I used `Vgr_svg` quite a bit. I guess I always ended up using the other transform primitives…

**Comment by dbuenzli** [comment]
If you want to use the fix immediately you should be able to do an `opam pin vg --dev`.

**Comment by johnridesabike** [comment]
Thanks for the quick fix!
